### ISSUE TITLE
word doubling

### ISSUE THREAD

**Issue by shahriarshafin** [learnwithsumit/vs-code-seetings-extensions#2]
I couldn't find your **Learn with Sumit Theme** [repository](https://github.com/learnwithsumit/learn-with-sumit-vscode-theme). That's why I created the issue here. <br>
`ext install learn-with-sumit-theme theme`-->`ext install learn-with-sumit-theme` <br> 
![image](https://user-images.githubusercontent.com/32214710/115630808-7ca1df00-a326-11eb-9aa6-8f6c643034c8.png)

**Comment by learnwithsumit** [comment]
Hi Shahriar, thanks for the report. The word doubling mistake was corrected.
Btw, you could not find the repository because the repository is not public. Thanks again and take care.

**Comment by shahriarshafin** [comment]
You are one of the best instructor I follow. Love your content 💛

**Comment by learnwithsumit** [comment]
Thanks a lot brother. Take love.
